# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SingleLineBlockParams:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/DotPosition:
  EnforcedStyle: trailing

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/PerlBackrefs:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/DoubleNegation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
