language: ruby
rvm:
  - 2.5.0
bundler_args: --jobs=2
script:
  - NODE_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake db:setup
  - bundle exec rake test
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
