language: ruby

branches:
  only:
    - master

rvm:
  - 2.5.1

bundler_args: --jobs=2

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.4"

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - NODE_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake db:setup
  - bundle exec rake test
