#! /bin/sh

cd api
scp docker-compose.yml rathr.io:/var/www/lists-docker
./build_and_push.sh

cd ui
REACT_APP_BACKEND_API_BASE_URL=https://lists.rathr.io/api yarn build
scp -r build rathr.io:/var/www/lists-docker/ui

ssh rathr.io 'bash --login -s' << "EOF"
  cd /var/www/lists-docker
  docker-compose down
  docker-compose pull
  docker-compose up -d
EOF
