version: '3'

services:
  redis:
    container_name: 'lists-redis'
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

  postgres:
    container_name: 'lists-db'
    image: 'postgres:11'
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    container_name: 'lists-web'
    entrypoint: [bin/entrypoint]
    image: 'rathrio/lists:latest'
    depends_on:
      - redis
      - postgres
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    env_file:
      - '.env.production'
    command: bundle exec rails server -p 3000 -b '0.0.0.0'


volumes:
  redis:
  postgres:
