# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production: &production
  notify_user_about_new_episodes_job:
    class: NotifyUserAboutNewEpisodesJob
    queue: background
    schedule: every day at noon
  refresh_season_metadata_job:
    class: RefreshSeasonMetadataJob
    queue: background
    schedule: every day at 3am
  random_recommendation_reminder_job:
    class: RandomRecommendationReminderJob
    queue: background
    schedule: every day at 6pm
  favorite_reminder_job:
    class: FavoriteReminderJob
    queue: background
    schedule: every monday at 6am

development:
  <<: *production
