production: &production
  notify_user_about_new_episodes_job:
    class: NotifyUserAboutNewEpisodesJob
    queue: background
    schedule: every day at noon
  refresh_season_metadata_job:
    class: RefreshSeasonMetadataJob
    queue: background
    schedule: every day at 3am
  random_recommendation_reminder_job:
    class: RandomRecommendationReminderJob
    queue: background
    schedule: every day at 6pm
  favorite_reminder_job:
    class: FavoriteReminderJob
    queue: background
    schedule: every monday at 6am
  release_reminder_job:
    class: ReleaseReminderJob
    queue: background
    schedule: every day at 6am


development:
  <<: *production
