# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/**
    - config/**
    - Gemfile

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/SingleLineBlockParams:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Layout/DotPosition:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/PerlBackrefs:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/DoubleNegation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
