#! /bin/bash

set -e

scp docker-compose.yml lists.rathr.io:/var/www/lists
./build_and_push.sh

ssh lists.rathr.io 'bash --login -s' << "EOF"
  cd /var/www/lists
  docker compose down
  docker compose pull
  docker compose up -d
EOF
