source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "net-smtp", require: false
gem "net-imap", require: false
gem "net-pop", require: false

# https://github.com/socketry/nio4r/issues/323
gem "nio4r", "~> 2.7", ">= 2.7.4"

# /Users/radi/.gem/ruby/3.3.4/gems/minitest-5.17.0/lib/minitest.rb:3: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of minitest-5.17.0 to add mutex_m into its gemspec.
gem "mutex_m"
gem "rails", "~> 8.0"
# Use postgres as the database for Active Record
gem "pg"
# Use Puma as the app server
gem "puma", "~> 6"
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'hiredis'
gem "redis" #, require: ["redis", "redis/connection/hiredis"]

# /Users/radi/.gem/ruby/3.4.5/gems/json-2.6.3/lib/json/generic_object.rb:2: warning: /Users/radi/.rubies/ruby-3.4.5/lib/ruby/3.4.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
# You can add ostruct to your Gemfile or gemspec to silence this warning.
gem 'ostruct'

# A fast JSON parser and Object marshaller.
gem "oj"

# CORS
gem "rack-cors"

# Tokens
gem "jwt"

# Authentication
gem "clearance"

# For attachments
gem "carrierwave"

# Imagemagick interface
gem "mini_magick"

# HTTP client
gem "csv"
gem "httparty"

# Softdelete
gem "paranoia"

# Active Job backend
gem "solid_queue", "~> 1.1"
# Dashboard for active jobs
gem "propshaft"
gem "mission_control-jobs", "~> 1.0"

# Faster boot time by caching expensive operations.
gem 'bootsnap', require: false

group :development, :test do
  gem "dotenv-rails"
  gem "observer"
  gem "factory_bot_rails"
  gem "ffaker"
end

group :development do
  gem "rubocop"
  gem "foreman"
  gem "web-console", "~> 4.2"
  gem "listen", "~> 3"

  # A documentation generation tool
  gem "yard"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
